# Generated by Django 5.1.6 on 2025-02-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0003_todo_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
