# Generated by Django 5.1.6 on 2025-02-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0005_todo_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
