# Generated by Django 5.1.6 on 2025-02-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0007_userprofilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfilemodel',
        ),
    ]
