# Generated by Django 5.1.6 on 2025-02-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0008_userprofile_email_delete_userprofilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
