# Generated by Django 5.1.6 on 2025-02-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0009_remove_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
