# Generated by Django 5.1.6 on 2025-02-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0011_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
