# Generated by Django 5.1.6 on 2025-02-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0013_userotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mob_no',
        ),
    ]
