# Generated by Django 5.1.6 on 2025-02-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0015_expiringtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('urgent', 'Urgent'), ('others', 'Others')], default='others', max_length=10),
        ),
    ]
