# Generated by Django 5.1.6 on 2025-02-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0017_todo_due_date_alter_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
