# Generated by Django 5.1.6 on 2025-03-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0021_remove_todo_reward_points_userprofile_total_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='total_points',
            new_name='points',
        ),
    ]
